[package]
name = "amber"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heraclitus-compiler = "1.5.1"
similar-string = "1.4.2"
colored = "2.0.0"
